### ISSUE TITLE
can not run query if disconnect while running a long query

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1251]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.4

3. The steps to reproduce this issue:

- run a long query
- disconnect
- reconnect

run query button became:

![image](https://user-images.githubusercontent.com/32751/59840081-4854e480-9384-11e9-9a22-af1a5d845806.png)

unable to run any query now.

**Comment by huyphams** [comment]
I'm not sure it was resolved in the beta release (I've updated the cancel queries) but I can't reproduce the bug anymore.
Download beta: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by georgexsh** [comment]
@huyphams new cancel feature is very cool, and I can't reproduce this issue.

**Comment by georgexsh** [comment]
this issue still exists but with different behavior, there is will be a never ending query, disconnect/reconnect doesn't work, close the corresponding tab may resolve this state.
![image](https://user-images.githubusercontent.com/32751/70424655-b021f780-1aaa-11ea-84aa-7972c8f36c61.png)
