### ISSUE TITLE
Auto theme support not respecting OS setting under macOS 10.15

### ISSUE THREAD

**Issue by tonyarnold** [TablePlus/TablePlus#1409]
I'm using TablePlus 2.8.3 (258), and the "Auto" theme setting remains dark when Catalina has switched to using the light appearance. 

<img width="1427" alt="Screen Shot 2019-09-03 at 13 02 53" src="https://user-images.githubusercontent.com/4802/64141373-25968000-ce4b-11e9-9102-c5e9782f7d80.png">

Manually changing to light or dark works as expected, so it appears that this bug only affects TablePlus when Catalina is set to use the "Auto" appearance, as shown in the screenshot above.

**Comment by huyphams** [comment]
We will check with Catalina, thanks @tonyarnold

**Comment by huyphams** [comment]
It's fixed now, it will be released in the next update or you can download the hotfix here:
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by tonyarnold** [comment]
Excellent, thanks @huyphams!

**Comment by thomasrotter** [comment]
Hi @huyphams,

I'm using 2.11.2 (279) and still have the same problem. Should this issue be already solved?

**Comment by huyphams** [comment]
Hmm, I couldn't reproduce the issue, I'm using Catalina and the build 279 too. Let me check it.

**Comment by thomasrotter** [comment]
Hi, @huyphams fyi I was able to fix it by switching in my macOS settings from auto to dark and back. Since then it works automatically ... don't know if that makes sense - but it solved it in my case.
