### ISSUE TITLE
Not loading extensions from resource file for SQLite

### ISSUE THREAD

**Issue by fintron** [TablePlus/TablePlus#1817]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

SQLite 3.27.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

build 300

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

*Background/setup:*
I downloaded and compiled the percentile.c extension from SQLite:
https://sqlite.org/src/raw/ext/misc/percentile.c?name=a6a1594c104da2d0ceab38fe609eb2f65529272377827f6f8a2b5c9fa6119e7e

And compiled it using:
`gcc -g -fPIC -dynamiclib percentile.c -o percentile.dylib`
(from: https://www.sqlite.org/loadext.html)

and loaded it in my .sqliterc file using:
`.load /Users/me/sqlite/percentile.dylib`

When creating the "Connection" in TablePlus, I also specified my .sqliterc file in the "Load Resource" section. 

*Current Issue*

If I use the regular sqlite3 CLI, I am able to use the compiled extension via:
`select percentile(cast (id as int), 50) from analysis;`

However, if I run the same query in TablePlus, I am getting the error:
```
Query 1 ERROR: no such function: percentile
```

This is indicating the TablePlus is not correctly loading extensions in the specified resource/sqliterc file.

**Comment by huyphams** [comment]
Apple does not allow us to hook dynamic lib at runtime (without signing), let me see to get it works.

**Comment by fintron** [comment]
If you can't hook the dynamic lib at runtime, could you just at least include the percentile.c when you're building the SQLite library you use in TablePlus? Percentile is a very useful useful function in SQL and this particular module is also built by the creator of SQLite

**Comment by fintron** [comment]
@huyphams - this open source library allows for loading extensions:
https://sqlitebrowser.org/
It seems like it's possible on Mac Apps. Could you try to add it to TablePlus?

**Comment by fintron** [comment]
There are actually a couple more:

Native SQLite Manager (in the app store)
https://apps.apple.com/us/app/native-sqlite-manager/id1416282836?mt=12

SQLite Studio

I don't think it's a limitation with MacOS

**Comment by huyphams** [comment]
Yes, there is an option (disabled by default), but it makes the app insecure. The attacker can hook any dynamic library into TablePlus app. Let me consider it. Thanks @fintron 

<img width="357" alt="Screen Shot 2020-05-02 at 9 08 20 PM" src="https://user-images.githubusercontent.com/3654622/80866498-3a1c6800-8cb9-11ea-9680-5bc3fbd2b436.png">

**Comment by chrschmitz** [comment]
Where is the option "Disable Library Validation" located? I can't find it. It would fit nicely in the "Crash & Security" preferences (I am using v3.4.0 (304)).

The option to load extensions is also disabled per default by SQLite itself. It has to be enabled by the user with a PRAGMA statement. Thus there is some sort of a double security layer.

I would appreciate it if you would allow users to enable this option. Currently, I have to move to another tool to get my work done.

**Comment by naturalethic** [comment]
How about allowing the user to specify which sqlite runtime to use?  This way they can select one they compiled themselves to allow extensions.

**Comment by anentropic** [comment]
I have the same problem trying to use Spatialite db with TablePlus

[Django](https://github.com/django/django/blob/b9cf764be62e77b4777b3a75ec256f6209a57671/django/contrib/gis/db/backends/spatialite/base.py#L38) does something like 
```python
conn.enable_load_extension(True)
# followed by
conn.load_extension("/usr/local/lib/mod_spatialite.dylib")
```

But in TablePlus when I try to `SELECT load_extension("/usr/local/lib/mod_spatialite.dylib");` I get:
```
ERROR: not authorized
```
It seems the `enable_load_extension(True)` call needs to be done in the application API level not via user SQL.

**Comment by n0rdlicht** [comment]
Support for using the spatialite extension in TablePlus would be super nice, since other GUI tools for this are very bad. 

Thanks @huyphams for considering it. Hope there is a way to get this working.

**Comment by JeanMertz** [comment]
This would be a nice feature to have. Specifically, I'm interested in using the [`uuid.c`](https://sqlite.org/src/file/ext/misc/uuid.c) extension.

**Comment by cleg** [comment]
This would be a really helpful feature, as macOS own build of sqlite is really limited in functionality. If custom extenstions/using custom sqlite3 build isn't possible, maybe TablePlus can use its own sqlite3 build with maximum extensions added? 
Another partial workaround — try to use sqlite3 from homebrew

**Comment by chrschmitz** [comment]
This thread is now open for more than 2 years. No way to enable the option to load extensions? I still can't use TablePlus, when I need the math extension (libsqlitefunctions.dylib).

**Comment by malinowskip** [comment]
I ran into a similar issue today (couldn’t use math functions in SQLite). It would be great if there was an option to provide a custom driver for SQLite.

Also, I just checked and if you build SQLite3 from source, then [math functions](https://www.sqlite.org/lang_mathfunc.html) are included by default, without the need to specify any additional build flags.

**Comment by vpoguru** [comment]
Unfortunately, the math functions are obviously not included in the current TablePlus builds. Including them by default would be great, as these functions are very useful.

**Comment by vpoguru** [comment]
I would like to go even one step further (an option available in DataGrip): it should be possible to open an extension automatically when a database is opened.

**Comment by Sytten** [comment]
Still an issue sadly. Is TablePlus really an attack vector?
I feel like it would be totally fine to allow unsigned libraries for a developer tool.

**Comment by davidemerritt** [comment]
+1 - I just ran into this and would love the option to load trusted sqllite extensions and take that risk on myself.

**Comment by norrye** [comment]
+1 loading spatialte is necessary for me

**Comment by halostatue** [comment]
Depending on the licences involved, it might also be worth considering *shipping* some extensions, such as those included in https://github.com/nalgeon/sqlean.

**Comment by huyphams** [comment]
Thanks guy for the feedback. I will consider it seriously in the next update. It should be fixed

**Comment by vpoguru** [comment]
Math functions are still not available in TablePlus 5.8.6 (Build 534), nor is it possible to load external extensions, such as [sqlean](https://github.com/nalgeon/sqlean/blob/main/docs/math.md). Integrated math functions have been introduced some time ago in [SQLite v3.35.0](https://www.sqlite.org/draft/releaselog/3_35_0.html).

What is the difficulty in integrating these functions into TablePlus?

**Comment by pbastowski** [comment]
@huyphams Is there any chance of getting the extension loading feature in the next TablePlus version?

**Comment by imajes** [comment]
just myself bumped into this with sqlean. Can we find a workaround please?

**Comment by eduardosanzb** [comment]
unfortunately; the lack of this feature forces me to stop recommending the license buying.

**Comment by huyphams** [comment]
TablePlus now allows to load side-lib on this patch https://www.dropbox.com/scl/fi/mpnhecs75ruoqe3442fpa/TablePlus.dmg?rlkey=594kh1wtsg85zmqcslim6jitj&dl=0

You can use that patch while waiting for the next official release.

So we will close this issue
