### ISSUE TITLE
Feature request: Multiple Results not in tabs but under each other like SQL Server Manager

### ISSUE THREAD

**Issue by DevZ1** [TablePlus/TablePlus#1826]
Hi,

first of all I think you did a great job on TablePlus and as a paying customer I use it more and more,
then I do SQL Server Manager.

The only thing which bothers me a bit is that multiple results are shown in Tabs and I have to click on them to see each result. Can this be done like SQL manager in windows and all result are shown in seperate grids under each other?

Thank you.

Regards, Hyko.

**Comment by huyphams** [comment]
y=Yes, we're refactoring this, basically, TablePlus will have three view mode.
1. Split into tabs.
2. Show only the last result.
3. Append all results in one tab.

TablePlus has the split-screen feature command + shift + D, just wanna make sure that you're aware of it.

**Comment by DevZ1** [comment]
Great to hear! I know about the split view, but not the same ;-)
When will this be available? Any ETR?

**Comment by huyphams** [comment]
I've implemented this feature on this hot patch, if you have a chance, please give it a try: https://www.dropbox.com/s/g801eovguzkqvlr/tableplus.dmg?dl=0
<img width="1709" alt="Screen Shot 2020-06-30 at 5 22 14 PM" src="https://user-images.githubusercontent.com/3654622/86115512-40cb2e00-baf6-11ea-8af6-602a363dbd38.png">

**Comment by DevZ1** [comment]
omg, thank you!! But how do I enable this. I still see tab output and no settings in setting to enabled this?

**Comment by huyphams** [comment]
Hey @DevZ1 you can enable this by checking this option!
<img width="555" alt="Screen Shot 2020-06-30 at 7 09 08 PM" src="https://user-images.githubusercontent.com/3654622/86124338-306e7f80-bb05-11ea-9d11-d803d272cd49.png">

**Comment by DevZ1** [comment]
OK, SQL Server Manager is officially dead for me 🥇  :-)
Great work, thank you!

**Comment by huyphams** [comment]
Thanks @DevZ1  feel free to give feedback so I can improve this feature better!

**Comment by DevZ1** [comment]
So far looks really good, but I will let you know when I can suggest some improvements.

**Comment by DevZ1** [comment]
![image](https://user-images.githubusercontent.com/4217221/86189733-b3fa9180-bb42-11ea-8cb8-688197ba0416.png)

I can edit the values in the last grid results, but not the first and I get this message..

**Comment by huyphams** [comment]
Thanks @DevZ1 could you please give me the query that TablePlus could not edit the query result?
