### ISSUE TITLE
Aliasing

### ISSUE THREAD

**Issue by phaistonian** [TablePlus/TablePlus#3399]
Hello,

(Please excuse me for not following the template.)

- Is there a way to force autocomplete from other databases? I can not do it at the moment.
- If not, can I assign some aliases (e.g., `pr` for `mydb.products`) to point to frequently used tables?

I am on the latest version (Version 6.1.6 (571))

Thank you

**Comment by huyphams** [comment]
Hi @phaistonian can you give us the step to reproduce the issue?

**Comment by phaistonian** [comment]
@huyphams, it's not an issue per se, more like a hassle. 

When working with multiple databases, you can not reference another database you have referenced in the query once already.

Also, more times than not you need to reference the same tables over and over again so having a way to aliasing them will hep a lot with productivity and sanity.

**Comment by huyphams** [comment]
It does suggest table in order db by you must type the dbname and a dot. That's why I am not sure what is th issue you're having

**Comment by phaistonian** [comment]
@huyphams  Sometimes the db name is long :) 

For example, one of those we use is named `bp10_materialized_views`. 

So imagine trying to type this over and over again.

ps: I have set up a text replacement mapping in OSX for this, but those are ignored in the editor, it seeems.

**Comment by huyphams** [comment]
TablePlus does suggest the db name too. And we should prefix the dbname when do the cross query, right?

**Comment by phaistonian** [comment]
This screencast will help illustrate the point :)


https://github.com/user-attachments/assets/5fb784f4-a152-41b3-99f5-46d7ba3a5ecc

**Comment by huyphams** [comment]
I am not sure if we can alias the db, but it is supported by MySQL, then TablePlus should support that syntax. (If not, it is a bug and we will fix it)

you can also create alias with the Queries keyword

**Comment by phaistonian** [comment]
> you can also create alias with the Queries keyword

Please, elaborate on this one.

**Comment by huyphams** [comment]
I'm not sure how to reproduce the issue, did you just create the db pb10_materialized_view, when the tab is already there? The database is not in the suggestion even after you restart the app?

<img width="906" alt="Screenshot 2024-09-27 at 7 25 50 PM" src="https://github.com/user-attachments/assets/b1a24af7-0f98-4f0b-b12c-bffbae88fbfb">

**Comment by huyphams** [comment]
> > you can also create alias with the Queries keyword
> 
> Please, elaborate on this one.

This

<img width="320" alt="Screenshot 2024-09-27 at 7 26 54 PM" src="https://github.com/user-attachments/assets/025ff74b-0cfc-4d66-8f88-e9fde1bc06c8">

**Comment by huyphams** [comment]
I think I can reproduce the issue. It happens when the user leaves the database field empty while creating the connection.

**Comment by huyphams** [comment]
> All the databases are there ....forever :)
> 
> Yes, it's not.
> 
> It is if I have selected the tab with the database itself - otherwise, it's not.

can you confirm that your current database (where it does not suggest any database name in the completion) has no tables?

**Comment by huyphams** [comment]
Hi @phaistonian I fixed the issue where the app didn't suggest the db name when the current database is empty (no item).

https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=quoqossi&dl=0

If you have a chance, please give it a try.

**Comment by phaistonian** [comment]
It seems the issue is still there - I am sure I am not explaining it properly, so this might help :)


https://github.com/user-attachments/assets/c2ea6a71-da7e-4ec9-847c-e6a17c082b29

**Comment by huyphams** [comment]
After I post the commend, I found an other issue with simple step.

1. Create connection without database (leave the db field empty).
2. Select a database in the database dropdown.
3. Open SQL => TablePlus will not suggest db name.

**Comment by phaistonian** [comment]
I am not sure this is related to this issue - perhaps, it is.

Does the video help at all?

**Comment by huyphams** [comment]
Unfortunately, it does not help as I could not see how you create the connection. The database field must be empty in order to reproduce the issue.

So that's why the step to reproduce is important. The steps above are the correct steps to reproduce the issue and I also believe it's the issue you're facing.

**Comment by huyphams** [comment]
Thanks you for the feedback @phaistonian if you have a chance, can you download and see how it goes

https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=quoqossi&dl=0

(the same dropbox link).

**Comment by phaistonian** [comment]
@huyphams  it seems that this one does it - though it failed a couple of times before it finally kicked in (i.e. had to restart a few times).

Kudos!:)

ps: will this be part of an newer release?

**Comment by huyphams** [comment]
Thank you for confirming. Yes, it will be included in the next update.

**Comment by phaistonian** [comment]
Oh, while at it, could you consider auto-selecting the first row here (it's usually one) when opening this modal?

![CleanShot 2024-09-27 at 20 48 18@2x](https://github.com/user-attachments/assets/0929bae0-3208-492b-b90d-0d2cc6efcd23)

9 times out of 10, you want to kill the query, so you need to select then kill.

**Comment by huyphams** [comment]
Hi @phaistonian I think it is a good idea but I will consider adding it. I remember that the reason I don't want to auto select first row because I want to avoid killing a query by mistake.
