### ISSUE TITLE
Windows PostgreSQL - Refresh Workspace does not refresh autocomplete

### ISSUE THREAD

**Issue by jmcadam-jd** [TablePlus/TablePlus#3546]
Two issues:

1. The autocomplete on Mac versions of TablePlus is excellent. It is one of the reasons I use this tool instead of pgAdmin or even JetBrains. HOWEVER, the autocomplete in Windows is absolutely awful. You should copy what you are doing on mac for windows.
2. [Windows] If you create a table and then refresh your workspace, it does not make your new table or columns appear in the autocomplete.

I hope you guys can prioritize this, quality of life features like this make people want to keep using your product, and it seems like the Windows version is poorly supported. :(

**Comment by huyphams** [comment]
All are fixed @jmcadam-jd 
Except the table and its columns not refresh, any other issues?

**Comment by jmcadam-jd** [comment]
Hi @huyphams

I just updated to the latest version of TablePlus on Windows [6.4.0 (300)] and the autocomplete is still not as good as MacOS.

Here are some screenshots to show how much longer it takes for Windows to find a good suggestion, please let me know if I can provide more detail.


**MAC:**

![Image](https://github.com/user-attachments/assets/9dcf9c8a-5005-4bdd-87de-1e27a86977c5)

**Windows:**

![Image](https://github.com/user-attachments/assets/aed2f1b5-2ba3-4be0-851a-b1bd0cce7787)

**Comment by jmcadam-jd** [comment]
@huyphams 
Do you know which TablePlus version we will see the update in?

Thank you!

**Comment by huyphams** [comment]
Please check build 302, thanks!
