### ISSUE TITLE
Repeatedly requested to enter private SSH key password

### ISSUE THREAD

**Issue by namxam** [TablePlus/TablePlus#412]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 9.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
104

3. The steps to reproduce this issue:
Create a new connection and tunnel it through SSH.

The app keeps requesting "Please enter SSH private key password". I can enter it multiple times but the popup keeps appearing. I am pretty sure it works, as other tools work with the exact same settings.

Is there anything I can do to debug the issue? Like getting extra log output?

**Comment by huyphams** [comment]
It keeps asking the passpharse that means you entered the wrong one or the current key was not match (or invalid) with the pass. Can you re-import the key and try over again? We didn’t have log on production build. :(

**Comment by huyphams** [comment]
Hey @yacinehmito can you re-select the id_rsa again? it's a weird bug. I can't reproduce.

**Comment by sebastianhelbig** [comment]
I am getting asked for key password, although my private key does not have any passphrase. This is with a 4096bit key. It works without problems with a 2048bit key.

**Comment by reefki** [comment]
I have also faced the same issue with no passphrase keys. It keeps asking the password.

**Comment by huyphams** [comment]
Hey guys,
I have a debug build here: https://www.dropbox.com/s/mf4b5auggb1lkvo/TablePlus.dmg?dl=0
You guy can run it and see the log for more detail with the command below:

- Open terminal:
/path_to_table_plus_app/TablePlus.app/Contents/MacOS/TablePlus

**Comment by huyphams** [comment]
I updated the build. now TablePlus reports the error more accurate. I also fixed the bug that can prevents TablePlus from saving passphrase.
Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by andresodio** [comment]
Are you sure the bug is fixed? I'm still getting it on build 256 of TablePlus. Thanks

**Comment by JoaquinScript** [comment]
@huyphams Still happening in build 264, can you reopen this issue?

**Comment by huyphams** [comment]
Hi, @JoaquinScript if TablePlus keeps asking password for the private key that means:
1. That key type isn't supported.
2. Wrong passphrase.

The original issue is related to the save passphrase issue to the keychain.

**Comment by JoaquinScript** [comment]
hey @huyphams thanks for the help. My use case is exactly the same as the OG comment: TablePlus keeps asking for SSH passphrase even though it doesn't have a passphrase. If I create a new connection it starts working again but at some point later it start asking for passphrase again.

**Comment by huyphams** [comment]
If it asks for the passphrase, could you please try to import the key again and let me know the result?

**Comment by JoaquinScript** [comment]
it works! don't know if it will be temporary or not, but I can update this issue if it starts again. Thanks @huyphams

**Comment by huyphams** [comment]
I think it's related to the keychain, TablePlus saves the ssh key into the keychain. I will take a look at it. Thank you.

**Comment by JoaquinScript** [comment]
@huyphams still happening on build 272, and now I can't even use the workaround of re-importing the key

**Comment by huyphams** [comment]
Please use ssh config @JoaquinScript as a workaround.  It seems like a new issue and not related to this one.
I will take a look at it.

**Comment by JoaquinScript** [comment]
still happening

**Comment by skatetdieu** [comment]
Same thing for me. Keeps asking me for password for ssh key even though it doesn't have one. I was using DBeaver and it works just fine there.

![Screen Shot 2020-03-24 at 11 01 18 AM](https://user-images.githubusercontent.com/1899636/77440523-cbe1ad00-6dbe-11ea-8c8a-9c93be7f3254.png)

**Comment by ryzr** [comment]
I'm also having issues when trying to use a public key that has been signed with [Netflix/bless](https://github.com/Netflix/bless).

Typically, I can just ssh with

```ssh user@server -i ~/.ssh/id_rsa```

In the debug logs, it seems to send id_rsa.pub and id_rsa-cert.pub

However when using ~/.ssh/config, or when specifying id_rsa manually in TablePlus, I'm asked to enter a passphrase, which I have not set.

**Comment by collegeman** [comment]
+1 for this issue. I'm not using a password with my key, and I keep getting asked for one anyway.

**Comment by malokroman** [comment]
Build 330 and still have the problem with ssh key password for mine not having one.

**Comment by scottishstoater** [comment]
Build 342, this bug is still present.

**Comment by nallwhy** [comment]
Build 371, still present.

**Comment by joostvanhoof** [comment]
I'm just now getting this as well after importing a server through a URL.

**Comment by darmen** [comment]
Same here for 1Password as an SSH agent implementation

**Comment by sitefinitysteve** [comment]
Same, okay... well it's not just me then

**Comment by SRK90** [comment]
same here. not working yet. 1password 8.8.0 & TablePlus 4.8.2

**Comment by nezaboravi** [comment]
This still exists. I don't have set passphrase.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/1515172/213121181-053f2397-2251-4332-bb93-e9912196879c.png">

**Comment by muuvmuuv** [comment]
On Mac, just use this in your terminal:

```
open -a TablePlus
```

**Comment by hauva007** [comment]
Build 504 and still present

**Comment by nezaboravi** [comment]
This is issue always present. for 2 years i am paying tableplus and this issue persists
<img width="494" alt="image" src="https://github.com/TablePlus/TablePlus/assets/1515172/9b7f6df7-7e57-4008-aba2-8849e9f1103e">

**Comment by ventrec** [comment]
Build 5.4.2
MacOs 12.7

Still an issue, and been an issue for a while. Seems to happen for me each time i restart the mac. I solved this by SSH'ing into a server with the private key. After doing that, TablePlus stopped prompting me for a passphrase. Seems to be related to keychain.

**Comment by vianneychin** [comment]
Updating TablePlus worked for me at least.

**Comment by dhaselhan-vrify** [comment]
Same issue here, using a key file with no passphrase and am constantly asked for one. I am unable to connect and have moved to a different tool without this issue.
