### ISSUE TITLE
Memory leak after idling

### ISSUE THREAD

**Issue by zanmato** [TablePlus/TablePlus#679]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server Web 14.0.1000.169

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 132

3. The steps to reproduce this issue:
Idling for long periods of time (overnight) **sometimes** makes TablePlus consume a lot of memory while _"Collecting database information.."_. In my case the DB I was connected to was restored during the night, so TablePlus probably tried reconnecting and got stuck.

<img width="600" alt="skarmavbild 2018-09-30 kl 21 34 09" src="https://user-images.githubusercontent.com/580791/46275780-66608780-c55e-11e8-89ac-9bc61bf491da.png">
<img width="586" alt="skarmavbild 2018-09-30 kl 21 34 23" src="https://user-images.githubusercontent.com/580791/46275781-66f91e00-c55e-11e8-9455-776083423280.png">

**Comment by huyphams** [comment]
Hi @zanmato can you update to the latest version of TablePlus (build 136)? I have fixed some memory leak issue on the latest build.

**Comment by zanmato** [comment]
@huyphams Yes, I've already updated. I'll see if still occurs and get back to you

**Comment by zanmato** [comment]
Tried leaving it on overnight again, and today I got _"Warning the server is taking too long to respond"_ with normal memory usage. Seems to be resolved,  thanks!

**Comment by arcyn1c** [comment]
Experiencing the same behavior under similar circumstances. Leaving TablePlus opened and connected overnight results in high memory usage and needing to force quit the application. I wonder if this may need to be reopened?

1. Driver
MySQL v5.x

2. Build number
v1.0 (166)

3. Steps to reproduce:
Connect to database. Leave overnight. Likely come back to high memory usage and TablePlus not responding. I leave work around 4pm and return the next morning at around 8:15, for reference. About 80% of the time I find TablePlus in an unresponsive state.

Sorry if I should be opening a new issue for this. I can if necessary!

**Comment by huyphams** [comment]
Thanks, @arcyn1c I will double check it.
