### ISSUE TITLE
Passwords not properly escaped for CLI usage

### ISSUE THREAD

**Issue by jmfederico** [TablePlus/TablePlus#739]
1. Which driver are you using and version of it: MySQL 5.7

2. Which TablePlus build number are you using: 142

3. The steps to reproduce this issue:

- Create a connection to a DB with a password like this one "apassword))withparentheses".
- Try to backup the database, you will get an error like:
```
Dump database done/bin/sh: -c: line 0: syntax error near unexpected token `)'
/bin/sh: -c: line 0: `cd /Applications/TablePlus.app/Contents/Resources && ./dump_ms_5.7 -h 127.0.0.1 -P 3306 -u user -apassword))withparentheses --compress database'
```

Usernames and passwords should be escaped before being used in the CLI.

**Comment by huyphams** [comment]
I fixed this issue on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks for letting me know.

**Comment by jmfederico** [comment]
I just tried the build form that download link and the problem persists when restoring Postgres databases

**Comment by jmfederico** [comment]
**Build number 163**

![screen shot 2018-12-08 at 11 28 26](https://user-images.githubusercontent.com/237977/49688264-4fe62780-fadd-11e8-8cdd-1df1a2903902.png)

I left parts of the password unredacted for you to see.

**Comment by jmfederico** [comment]
If the password contains an a dollar sign ($) also generates problems, since it might get expanded.
