### ISSUE TITLE
Export SQL & Import from SQL dumps

### ISSUE THREAD

**Issue by unixzilla** [TablePlus/TablePlus#906]
I got Error when i import from SQL dumps by TablePlus Export.

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '["CREATE TABLE ...... "];`

I think Export SQL function added the pair of square buckets. 

I have to use text editor to open SQL dump file to remove those square buckets and "\n" to fix import table.

**Comment by huyphams** [comment]
Hi @unixzilla TablePlus uses the table creation queries which are returned by MySQL so I think it can't be wrong. Could you send me an example via email huy@tableplusapp.com ?
Thank you so much!

**Comment by quoted-be** [comment]
I have the same issue, I try to export a table and then re-import, but an SQL error is thrown...

<img width="599" alt="screenshot 2019-01-24 at 15 01 59" src="https://user-images.githubusercontent.com/47000624/51683733-cafe9100-1fea-11e9-915b-5d4214402bd2.png">

**Comment by huyphams** [comment]
Hi @quoted-be @unixzilla I've fixed the bug on this build here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks!

**Comment by sietzekeuning** [comment]
Thanks, that fix works perfect!

**Comment by pactode** [comment]
This issue still persists on the recently installed version using Setapp or brew. 

![image](https://user-images.githubusercontent.com/5956778/129545373-4a91f16b-aac9-4cbe-b5d3-7acd0346704b.png)
![image](https://user-images.githubusercontent.com/5956778/129545516-e129a9c0-4c87-4c45-a833-0aea309a0483.png)

**Comment by huyphams** [comment]
It could be a different issue, could you please tell us your setup @pactode?

**Comment by pactode** [comment]
Sure, I'm connecting to a managed MySQL server on Digital Ocean and exporting the data using TablePlus GUI. When I try to import the file is invalid due to using double quotes " instead of single quotes ` in the create table statements.

Invalid SQL, which is from using the export using the GUI:
```sql
DROP TABLE IF EXISTS "attention_texts";
CREATE TABLE "attention_texts" (
  "id" bigint unsigned NOT NULL AUTO_INCREMENT,
  "title" varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  "created_at" timestamp NULL DEFAULT NULL,
  "updated_at" timestamp NULL DEFAULT NULL,
  "created_by" bigint unsigned DEFAULT NULL,
  "updated_by" bigint unsigned DEFAULT NULL,
  PRIMARY KEY ("id"),
  KEY "attention_texts_created_by_index" ("created_by"),
  KEY "attention_texts_updated_by_index" ("updated_by"),
  CONSTRAINT "attention_texts_created_by_foreign" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE CASCADE,
  CONSTRAINT "attention_texts_updated_by_foreign" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON DELETE CASCADE
);
```

When I search and replace double quotes (") with ` it works:
```sql
DROP TABLE IF EXISTS `attention_texts`;
CREATE TABLE `attention_texts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `attention_texts_created_by_index` (`created_by`),
  KEY `attention_texts_updated_by_index` (`updated_by`),
  CONSTRAINT `attention_texts_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `attention_texts_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
```

**Comment by huyphams** [comment]
I think this issue is not a TablePlus issue, TablePlus fetch table creation from the database and your database server is using double quote instead of backstick. You can change it back here: 

https://stackoverflow.com/questions/13884854/mysql-double-quoted-table-names

**Comment by huyphams** [comment]
Here is the MySQL documents: https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_ansi_quotes

**Comment by pactode** [comment]
Thanks! I'll take a look at that.

**Comment by pactode** [comment]
@huyphams It still exports the data using double quotes although the `ANSI_QUOTES` mode is enabled. Any ideas?

**Comment by huyphams** [comment]
Maybe you should disable it @pactode

**Comment by pactode** [comment]
@huyphams Thanks! That did the trick. 👍
