### ISSUE TITLE
Can't connect to any MongoDB instance

### ISSUE THREAD

**Issue by ffxsam** [TablePlus/TablePlus#929]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MongoDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 188

3. The steps to reproduce this issue:
I'm unable to connect to any MongoDB. "Authentication failed" pops up, with no details, so I can't figure out how to troubleshoot it.

Side note: It would be great to have an option to paste a MongoDB URI. With replica sets, it gets more complicated entering credentials, and in fact, you want the user to input all the hostnames used in the replica set.

**Comment by ffxsam** [comment]
I'm trying to connect to an mLab instance.

**Comment by huyphams** [comment]
Probably your password includes some special characters and this is one of the known issues. We will fix it on the next update. Thanks @ffxsam

**Comment by ffxsam** [comment]
Nope, just alphanumeric. Keep up the great work, love the updates!

**Comment by huyphams** [comment]
I've added the auth mechanism on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
I'm not sure if it was the problem but I think it worth to try:
<img width="612" alt="screen shot 2019-02-02 at 2 02 35 am" src="https://user-images.githubusercontent.com/3654622/52143653-9e074980-268e-11e9-806a-f04e3cb2a60c.png">

**Comment by huyphams** [comment]
I added auth mechanism, I think it's fixed now. Please let me know if it doesn't work and I will reopen this issue.

**Comment by ffxsam** [comment]
It's not fixed, sorry :( Build 190 still not working.

![image](https://user-images.githubusercontent.com/12532733/52182467-2129bc00-27c3-11e9-846f-b68aec7c33f8.png)

**Comment by ffxsam** [comment]
I would suggest creating a free mLab instance to test this out.

**Comment by huyphams** [comment]
Updated for people who are searching for this issue:
Please download this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
This build support auth source, Mlab requires auth source when creating a connection.

**Comment by vkononov** [comment]
@huyphams The data export does not work for this version from a Mongo collection. It creates an empty file. The only way it works is if you select documents manually and right click to export.

**Comment by timetorock** [comment]
* Which driver are you using and version of it (Ex: PostgreSQL 10.0): MongoDB
* Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 190/193
* The steps to reproduce this issue:
  I'm unable to connect to any MongoDB. "Authentication failed" pops up, with no details, so I can't figure out how to troubleshoot it.

I can't connect to MongoDB hosts on:
- Local Docker instance
- Host at my company via ssh. SSH part success, but next same error as in first case.

I really like your application, in case of MySQL it works fine for me, but I need it to work with MongoDB too. I'm ready to help with debug.

**Comment by huyphams** [comment]
Hi @timetorock could you send me a screenshot of your connection form to my email huy@tableplusapp.com (please change or blur the sensitive information if needed)
Thanks

**Comment by timetorock** [comment]
@huyphams thank you for help, when I specify my **database name** in **auth source** and it started to work. But now there are two same strings in config.

@huyphams By default you can try to substitute it automatically in auth source 👍

**Comment by huyphams** [comment]
Enhancement should be another issue, thanks guy for all the feedbacks. 👍

**Comment by scarlac** [comment]
It's not clear what "Auth source" is. I would never have thought to enter the database name there but @timetorock 's advice to do so made it work.

**Comment by ffxsam** [comment]
Right. Auth source (if left blank) should just be the database name. This is how most Mongo clients work under the hood. (leaving it blank in Table Plus shouldn't be an error)
