### ISSUE TITLE
wrong sql query while updating when data_type is timestamp and column_default is CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by kamekazemaster** [TablePlus/TablePlus#960]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
190

3. The steps to reproduce this issue:
Create a column with data_type "timestamp" with is_nullable = NO and column_default = NOW(). Then set "on update CURRENT_TIMESTAMP". Save. Then try to remove the "on update CURRENT_TIMESTAMP". The error message is "Invalid default value for 'created'
All changes were reverted."

The resulting SQL query is the following:
```SQL
ALTER TABLE `dbName`.`tableName` CHANGE `created` `created` timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT '';
```

whereas it should be:
```SQL
ALTER TABLE `dbName`.`tableName` CHANGE `created` `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '';
```

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @kamekazemaster we fixed some bug related on this issue on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Could you give it a try?

**Comment by kamekazemaster** [comment]
Seems to be still the same. When I try to readd the "on update CURRENT_TIMESTAMP" TablePlus generates me the following SQL query:
```SQL
ALTER TABLE `easycardealer`.`document_v2` CHANGE `created` `created` timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP' ON UPDATE CURRENT_TIMESTAMP COMMENT '';
```

**Comment by huyphams** [comment]
You add it via advanced...> constant or expression? it should be expression

**Comment by kamekazemaster** [comment]
I am not trying to edit the column_default but to edit the extra field. It should be necessary to touch the column_default field if I only want to update the extra field.

**Comment by huyphams** [comment]
You can use NOW() in the column_default, it will be the same with `CURRENT_TIMESTAMP`
I'm adding a new option on column_default to make it easier
<img width="444" alt="screen shot 2019-02-09 at 7 35 53 pm" src="https://user-images.githubusercontent.com/3654622/52520919-f1d2ed80-2ca1-11e9-8eea-80ec4dfc2011.png">

**Comment by kamekazemaster** [comment]
When creating a new field there isn't an option for `CURRENT_TIMESTAMP` but for `NOW()`. After saving the updates to the table it changes the value from `NOW()` to `CURRENT_TIMESTAMP`. After that it shouldn't be necessary to touch this field again when trying to update another field, e.g. the extra field.
![image](https://user-images.githubusercontent.com/3775931/52520949-2037d500-2c70-11e9-8256-e97b2c1da7f7.png)

**Comment by huyphams** [comment]
I just added `CURRENT_TIMESTAMP` so it isn't included on that build. `NOW()` -> `CURRENT_TIMESTAMP` is MySQL default

**Comment by huyphams** [comment]
I just released build 194 official, which includes this fix. Thanks.
