### ISSUE TITLE
Bug require login too frequently

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus#98]
TablePlus requires sign-in after open/upgrade app.

**Comment by huyphams** [comment]
I have pushed a backend fix to extend TTL of token.

**Comment by JeppeKnockaert** [comment]
This issue still exists. Every time I update TablePlus, I need to login again.

**Comment by huyphams** [comment]
Hi @JeppeKnockaert TablePlus stores the token key in the keychain.
Can you open the keychain and search `TablePlus-token` then delete the key and start the app again?

**Comment by JeppeKnockaert** [comment]
I have no TablePlus-token entry, but I do have a lot of "TablePlus" entries. I've deleted all of them and restarted the app. I'll have to wait until the next update to see if this fixed my issue. I will report back to you at that time.

**Comment by huyphams** [comment]
The other entries are connection passwords if you deleted them all that means you should enter it again in the connection form 😱

**Comment by JeppeKnockaert** [comment]
Yeah, I figured, no problem though 😛

**Comment by JeppeKnockaert** [comment]
Seems to be fixed, I updated without having to log in again, thanks for the help!
